apiVersion: v1
kind: Pod
metadata:
  name: curlpod
  namespace: ollama
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]

