# src/knowledge_bot/config/tasks.yaml
ingest_task:
  description: >
    Collect documents from local folder, optional GitHub URL, and optional Google Drive folder
  expected_output: >
    Dictionary with 'documents' list and 'count' of processed files

embed_task:
  description: >
    Chunk, embed using Ollama embeddings, and upsert into a persistent Chroma collection
  expected_output: >
    Dictionary with 'embedded' count and 'collection' name

query_task:
  description: >
    Retrieve top-k similar chunks and answer the question via Ollama with optional OpenAI fallback
  expected_output: >
    Dictionary with 'answer' text and 'sources' metadata list

